import Foundation

private final class AppResourcesBundleFinder {}

/// Resource bundle locator for assets generated by the SwiftPM build.
///
/// The default `Bundle.module` accessor that `swift build` emits only
/// considers two candidate paths:
///   1. `Bundle.main.bundlePath` + "/<Pkg>_<Target>.bundle"
///   2. The build dir hardcoded into the binary at compile time
///
/// For a packaged `.app`, `Bundle.main.bundlePath` is the `.app` root
/// itself — NOT `Contents/Resources/`. Placing the bundle at the .app
/// root is not an option either: codesign rejects it with
/// "unsealed contents present in the bundle root". The standard macOS
/// layout requires resources under `Contents/Resources/`, which neither
/// of `Bundle.module`'s candidates resolves. Result: the app crashes on
/// first asset lookup with
///   Fatal error: could not load resource bundle: from
///   /Applications/DripMeter.app/DripMeter_DripMeter.bundle or ...
///
/// This accessor checks `Bundle.main.resourceURL` (i.e. `.app/Contents/
/// Resources/`) first so packaged builds work, and falls back to
/// `Bundle.module` for `swift run` / `swift test` / Xcode previews,
/// where the SwiftPM-generated accessor's build-dir candidate is the
/// one that resolves.
enum AppResources {
    static let bundle: Bundle = {
        let bundleName = "DripMeter_DripMeter"

        let candidates: [URL] = [
            Bundle.main.resourceURL,
            Bundle(for: AppResourcesBundleFinder.self).resourceURL
        ]
        .compactMap { $0?.appendingPathComponent("\(bundleName).bundle") }

        for url in candidates where FileManager.default.fileExists(atPath: url.path) {
            if let bundle = Bundle(url: url) {
                return bundle
            }
        }

        return .module
    }()
}
